import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

let store = new Vuex.Store({
    state: {
        que: '',
        "plants": [
            {
                "id": 1,
                "lat_name": "Abies holophylla",
                "rus_name": "Пихта цельнолистная",
                "src": "21 24 26",
                "descr": "Вид описан в 1866 г. К. И. Максимовичем. В культуру введён в 1905 г. (G. Krussmann (1995)). По данным в первом томе «Деревья и кустарники СССР» (Васильев, Уханов, 1949, с. 80), тогда, к середине XX в., была известна в культуре единичными экземплярами лишь в Ленинграде, в Лесотехнической академии.",
                "pict": "https://www.plantarium.ru/dat/plants/2/238/684238_5503dae0.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/2/258/566258_9fa8cff3.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/2/260/566260_bf5fd7d3.jpg",
                "divisio": "Pinophyta",
                "classis": "Pinopsida",
                "ordo": "Pinales",
                "familia": "Pinaceae",
                "otdel": "Хвойные",
                "class": "Пинопсиды",
                "otrad": "Сосновые",
                "semeistvo": "Сосновые",
                "garden_id": "1",
            },
            {
                "id": 2,
                "lat_name": "Malus floribunda",
                "rus_name": "Яблоня обильноцветущая",
                "src": "21 24 26",
                "descr": "Годы пребывания в коллекции Сада: до 1858-1881, около 1930–1965 и с 1983 г. по настоящее время (Связева, 2005). Здесь появилась раньше чем в других Европейских коллекциях. A. Rehder (1949) приводит более позднюю дату – 1862 г",
                "pict": "https://www.plantarium.ru/dat/plants/5/576/699576_5b926b01.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/5/569/699569_2435b6b4.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/1/178/244178_e4ed2fce.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Rosales",
                "familia": "Rosaceae",
                "otdel": "Покрытосеменные",
                "class": "Двудольные",
                "otrad": "Розоцветные",
                "semeistvo": "Шиповниковые",
                "garden_id": "1",
            },
            {
                "id": 3,
                "lat_name": "Juniperus rigida",
                "rus_name": "Можжевельник твёрдый",
                "src": "21 24 26",
                "descr": "Вид описан в 1866 г. К. И. Максимовичем. В культуру введён в 1905 г. (G. Krussmann (1995)). По данным в первом томе «Деревья и кустарники СССР» (Васильев, Уханов, 1949, с. 80), тогда, к середине XX в., была известна в культуре единичными экземплярами лишь в Ленинграде, в Лесотехнической академии.",
                "pict": "https://www.plantarium.ru/dat/plants/9/974/631974_8b4148ee.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/3/309/650309_a4f2fc23.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/2/233/223233_c3af3874.jpg",
                "divisio": "Pinophyta",
                "classis": "Pinopsida",
                "ordo": "Cupressales",
                "familia": "Cupressaceae",
                "otdel": "Хвойные",
                "class": "Пинопсиды",
                "otrad": "Кипарисовые",
                "semeistvo": "Кипарисовые",
                "garden_id": "1",
            },
            {
                "id": 4,
                "lat_name": "Betula medwediewii",
                "rus_name": "Берёза Медведева",
                "src": "21 24 26",
                "descr": "В Саду: 1893-1923, 1954-1968 (Связева, 2005). А. Rehder (1949) приводит более позднюю дату – 1897 г",
                "pict": "https://www.plantarium.ru/dat/plants/7/774/698774_738da169.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/0/046/710046_c49ebbfb.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/7/713/672713_97b581d4.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Corylales",
                "familia": "Betulaceae",
                "otdel": "Покрытосеменные",
                "class": "Двудольные",
                "otrad": "Лещиноцветные",
                "semeistvo": "Берёзовые",
                "garden_id": "1",
            },
            {
                "id": 5,
                "lat_name": "Caragana arborescens",
                "rus_name": "Жёлтая акация",
                "src": "21 24 26",
                "descr": "По мнению О. А. Связевой (2005), с 1736 г., а возможно и раньше, постоянно растет в Саду. Появилась после экспедиции Даниэля Мессершмидта в Сибирь в 1727 г. Здесь впервые введена в культуру. Мессершмидт вернулся в Санкт-Петербург еще до создания Ботанического сада Петербургской Академии наук (существовал с 1735 по 1812 гг.), сборы экспедиции поступили в Аптекарский огород (Firsov, 1999).",
                "pict": "https://www.plantarium.ru/dat/plants/5/525/685525_afd716ea.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/5/522/685522_3d7b77f7.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/7/785/653785_5bdf5f2e.jpg",
                "divisio": "Pinophyta",
                "classis": "Pinopsida",
                "ordo": "Cupressales",
                "familia": "Cupressaceae",
                "otdel": "Хвойные",
                "class": "Пинопсиды",
                "otrad": "Кипарисовые",
                "semeistvo": "Кипарисовые",
                "garden_id": "1",
            },
            {
                "id": 6,
                "lat_name": "Cynara Scolymus",
                "rus_name": "Артишок настоящий",
                "src": "-",
                "descr": "Петр 1 попробовал артишоки в Голландии с каким-то сложным соусом. Ему они очень понравились, и он привёз эти теплолюбивые растения в Петербург. В холодном климате северо-запада артишоки, естественно, не плодоносили. Садовники, помучавшись, изобрели технологию выращивания артишоков в 1719г.: выкапывалась траншея глубиной 70 см,  на дно которой укладывался свежий конский навоз высотой 50 см, засыпался 20 см перегноя, сажались артишоки и сверху грядка опять укрывалась 5 см  теплого конского навоза, который периодически (1 раз в пять дней) меняли на свежий. Только так можно было получить урожай.",
                "pict": "https://www.plantarium.ru/dat/plants/9/939/67939_88827b4d.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/7/750/726750_5764c33b.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/3/358/555358_cd842e83.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Asterales",
                "familia": "Asteraceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Астроцветные",
                "semeistvo": "Астровые",
                "garden_id": "2",
            },
            {
                "id": 7,
                "lat_name": "Asteraceae",
                "rus_name": "Латук посевной",
                "src": "-",
                "descr": "Салаты-латуки русскому человеку не нравились. Один из управляющих мызой писал: «Мы не козлы, дабы жрать эту траву». Салаты выращивали и продавали иностранцам – немцам, французам, итальянцам. Интересно, что тогда же на Руси весной ели лебеду, щавель, крапиву, листья маргаритки. Понадобилось около 100 лет, чтобы культура салатов вошла в рацион.",
                "pict": "https://www.plantarium.ru/dat/plants/7/707/12707_b19de0c1.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/4/404/711404_bc6ba09f.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/4/403/711403_53387f48.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Asterales",
                "familia": "Asteraceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Астроцветные",
                "semeistvo": "Астровые",
                "garden_id": "2",
            },
            {
                "id": 8,
                "lat_name": "Raphanus sativus",
                "rus_name": "Редька посевная",
                "src": "-",
                "descr": "Редис настолько понравился царю, когда он попробовал его в Голландии, что был издан именной указ: в любое время года, в любой точке России он должен присутствовать на царском столе в количестве не менее 5 штук.",
                "pict": "https://www.plantarium.ru/dat/plants/0/000/13000_2ebcd765.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/1/101/661101_89dd1f65.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/1/170/624170_a823bb31.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Capparales",
                "familia": "Brassicaceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Капустоцветные",
                "semeistvo": "Капустные",
                "garden_id": "2",
            },
            {
                "id": 9,
                "lat_name": "Tulipa greigii",
                "rus_name": "Тюльпан Грейга",
                "src": "-",
                "descr": "В Россию тюльпаны в начале XVIII века привез Петр I. Он даже создал специальную компанию, занимавшуюся экспортом этих цветов из Нидерландов. В Петербурге тюльпаны высаживали по приказу Императора в только основанном Летнем саду.",
                "pict": "https://www.plantarium.ru/dat/plants/0/047/12047_fbe7200b.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/4/485/693485_3c8ef0a7.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/8/838/651838_018de246.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Liliopsida",
                "ordo": "Liliales",
                "familia": "Liliaceae",
                "otdel": "Цветковые",
                "class": "Однодольные",
                "otrad": "Лилиецветные",
                "semeistvo": "Лилейные",
                "garden_id": "2",
            },
            {
                "id": 10,
                "lat_name": "Solanum tuberosum",
                "rus_name": "Паслён клубненосный",
                "src": "-",
                "descr": "Особое внимание уделялось привезенным Петром 1 картофелю («земляным яблокам»). По легенде, первые четыре мешка картофеля Петр 1 посадил сам в Стрельне в 1711 году. Правда, стал популярным картофель только во времена Екатерины 2. 5-конечный цветок картошки носили как украшение.",
                "pict": "https://www.plantarium.ru/dat/plants/4/476/258476_db3fbe07.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/2/260/741260_d5ca16dd.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/5/512/720512_4ac90b14.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Solanales",
                "familia": "Solanaceae",
                "otdel": "Покрытосеменные",
                "class": "Двудольные",
                "otrad": "Паслёноцветные",
                "semeistvo": "Пасленовые",
                "garden_id": "2",
            },
            {
                "id": 11,
                "lat_name": "Ananassa sativa",
                "rus_name": "Ананас посевной",
                "src": "-",
                "descr": "В Подлипском саду находились теплицы, в которых росли фиговые, персиковые, абрикосовые, померанцевые и лавровые деревья, травы и цветы. В теплицах выращивались ананасы, дыни, арбузы, ранние огурцы, здесь же располагались овощные грядки, размер которых был прописан указом Петра I – 3 сажени на 0,5 сажени (6 х 1,10 м) на «голландский манер».",
                "pict": "https://www.plantarium.ru/dat/plants/7/784/426784_521056d8.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/3/391/638391_29932a7d.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/7/781/426781_890f8089.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Liliopsida",
                "ordo": "Bromeliales",
                "familia": "Bromeliaceae",
                "otdel": "Цветковые",
                "class": "Однодольные",
                "otrad": "Злакоцветные",
                "semeistvo": "Бромелиевые",
                "garden_id": "3",
            },
            {
                "id": 12,
                "lat_name": "Quercus robur",
                "rus_name": "Дуб черешчатый",
                "src": "-",
                "descr": "Первыми деревьями нового сада были ели, а также дубы для осушения заболоченной территории участка.",
                "pict": "https://www.plantarium.ru/dat/plants/8/851/690851_01211fb5.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/7/780/759780_07b43d0f.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/6/636/732636_62270bd3.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Fagales",
                "familia": "Fagaceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Букоцветные",
                "semeistvo": "Буковые",
                "garden_id": "3",
            },
            {
                "id": 13,
                "lat_name": "Citrullus lanatus",
                "rus_name": "Арбуз обыкновенный",
                "src": "-",
                "descr": "Император к сладкому был равнодушен. На десерт он предпочитал есть свежие фрукты и ягоды. Десерт мог состоять из одних арбузов. Ягоду Пётр очень любил и ел её в любом виде. И, опять же, пристрастие императора отразилось на гастрономическом производстве. Пётр I построил несколько теплиц для выращивания арбузов. Можно сказать, что современный арбузный август — продолжение традиции, заложенной Петром.",
                "pict": "https://www.plantarium.ru/dat/plants/9/951/162951_26dcc8c7.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/1/156/744156_add52dbc.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/1/160/744160_86b25801.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Cucurbitales",
                "familia": "Cucurbitales",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Тыквоцветные",
                "semeistvo": "Тыквенные",
                "garden_id": "3",
            },
            {
                "id": 14,
                "lat_name": "Citrus sinensis",
                "rus_name": "Цитрус китайский",
                "src": "-",
                "descr": "Екатерина Алексеевна посылала в подарок Петру за границу оранжерейные «цитроны», «аплицыовины» (апельсины), «винные ягоды» (виноград), ... с припиской: «Хотя и есть в земле обетованной довольно хороших фруктов, однако …наши приятнее вам будут».",
                "pict": "https://www.plantarium.ru/dat/plants/4/491/124491_aa1943f7.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/5/531/600531_ee46a64e.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/6/691/758691_7b630d89.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Rutales",
                "familia": "Ruteceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Сапиндоцветные",
                "semeistvo": "Рутовый",
                "garden_id": "3",
            },
            {
                "id": 15,
                "lat_name": "Vitis vinifera",
                "rus_name": "Виноград культурный",
                "src": "-",
                "descr": "Петр I выпустил целую серию указов, в которых повелевал местным воеводам помимо прочего активно развивать виноградарство и виноделие на вверенных им территориях. При этом для вин император указывал завести виноградники в Гребенях, а Астраханский виноград использовать для виноградной водки. Сохранился и текст указа: «которые виноградные сады при Астрахани, из того делать горячее вино, а вместо того для вин завести виноградные же сады в Гребенях; и того ради послать туда мастеров тех, которые в Астрахани, и чтобы оные там обыскали удобные для оного места, а из готового сделали бы пробу».",
                "pict": "https://www.plantarium.ru/dat/plants/7/796/184796_367544de.jpg",
                "pict1": "https://www.plantarium.ru/dat/plants/7/714/763714_ff8c8d8c.jpg",
                "pict2": "https://www.plantarium.ru/dat/plants/5/551/753551_ab77bc2c.jpg",
                "divisio": "Magnoliophyta",
                "classis": "Magnoliopsida",
                "ordo": "Vitales",
                "familia": "Vitaceae",
                "otdel": "Цветковые",
                "class": "Двудольные",
                "otrad": "Виноградоцветные",
                "semeistvo": "Виноградовые",
                "garden_id": "3",
            },
        ],
        otdels: [
            {name: 'Хвойные', pic: 'Хвойные.jpg'},
            {name: 'Покрытосеменные', pic: 'Покрытосеменные.jpg'},
            {name: 'Цветковые', pic: 'Цветковые.jpg'},
            {name: 'Аскомицеты', pic: 'Аскомицеты.png'},
            {name: 'Базидиомицеты', pic: 'Базидиомицеты.jpg'},
            {name: 'Моховидные', pic: 'Моховидные.jpg'},
            {name: 'Печёночные мхи', pic: 'Печёночные_мхи.jpg'},
            {name: 'Папоротниковидные', pic: 'Папоротниковидные.jpg'},
        ],
        gardens: [
            {name: "Ботанический сад Петра Великого", id: 1, jpg: 'PetrGarden.jpg'},
            {name: "Стрельна", id: 2, jpg: 'StrelnaGarden.jpg'},
            {name: "Летний сад", id: 3, jpg: 'SummerGarden.jpg'},
        ]
    },
    mutations: {
        SET_PRODUCTS_TO_STATE: (state, plants) => {
            state.plants = plants
        }
    },
    actions: {},
    getters: {
        PLANTS(state) {
            return state.plants
        },
        ONE_PLANT(state, id) {
            return state.plants.find(p => p.id === id)
        },
        OTDELS(state) {
            return state.otdels
        },
        GARDENS(state) {
            return state.gardens
        }
    }
});

export default store;